### PR TITLE
More elaborate scores

### PR DESCRIPTION
**Pull request by daanwerf**
The score system now rewards less points to the player if he has eaten more fishes. This means that the player has to eat fishes that are close as possible in size to the size of the player. This will encourage the player to take more risk in order to get the highest possible score. I have also fixed the new highscore not displaying and some text that was shown at the same location in both the losepane and the winpane.

### CODE REVIEW

**Comment by Exclaminator** [comment]
Why would you let the panes throw exceptions instead of logging it themselfs and displaying perhaps an error on the pane?

**Comment by SytzeAndr** [comment]
I approve

**Comment by Exclaminator** [comment]
Please fix the issues I reported

**Comment by daanwerf** [comment]
I would rather call them suggestions instead of issues, but I did implement what you said. You can check them now.

**Comment by Exclaminator** [comment]
Yes, could you then finaly check my branch..

**Comment by daanwerf** [comment]
Both done, I will leave a comment on your branch as soon as i get back home

**Comment by Exclaminator** [comment]
I would like to merge, but it has Merge conflicts now, please fix this first.

**Pull request merged**
