### PR TITLE
Resolution

### PR DESCRIPTION
**Pull request by SytzeAndr**
now the build is not failing anymore.

The bug had to do with Maven trying to extract the resolution of the user's screen, but as maven doesn't have one it throws an exception. This exception was not caught, so I implemented a try catch.

### CODE REVIEW

**Comment by Exclaminator** [comment]
Looks Realy Realy good! has my axe!

**Comment by Exclaminator** [comment]
Next time please rename the branch acordingly when shifing focus!

**Comment by SytzeAndr** [comment]
Due to merge conflicts with youri's branch, I first have to resolve this.

**Comment by SytzeAndr** [comment]
I resolved the merge conflicts, could you look at it again?

**Comment by Exclaminator** [comment]
The changes are minimal and I accept them

**Comment by MichielvdBerg** [comment]
Checked

**Pull request merged**
