### PR TITLE
End screen

### PR DESCRIPTION
**Pull request by SytzeAndr**
made an end screen similar to the winning screen. It's a bit of barbarian way of coding, and a task for the next sprint will be to organize our code better. But hey, it is working

### CODE REVIEW

**Comment by spiderbiggen** [comment]
please fix your checkstyle errors

**Comment by SytzeAndr** [comment]
done, could you look at it again?

**Comment by spiderbiggen** [comment]
looks good

**Comment by Exclaminator** [comment]
Jup, merging

**Pull request merged**
