### PR TITLE
Gui tests revamped

### PR DESCRIPTION
**Pull request by Exclaminator**
Gui tests now work by the principle of induction.

### CODE REVIEW

**Comment by Exclaminator** [comment]
Also removed randomization from concurrency

**Comment by SytzeAndr** [comment]
The code looks good, but I am reviewing this on my phone. I haven't managed to look at it in my ide. Apart from making gui tests, you also added some code in other classes. is this pure for testing purposes?

**Comment by Exclaminator** [comment]
There where some concurreny problems wich made the seeds for the random
function not enough to manipulate them. The extra code is to solve the
problems caused by concurrency.

**Comment by SytzeAndr** [comment]
If everything works correct, you can merge.

**Comment by daanwerf** [comment]
Looks good to me. Nice work on removing any possible randomness in these tests.

**Pull request merged**
