### PR TITLE
Tests from under to top

### PR DESCRIPTION
**Pull request by SytzeAndr**
This branch contains some more tests

### CODE REVIEW

**Comment by MichielvdBerg** [comment]
Checked, the next person can merge if he thinks its good.

**Comment by spiderbiggen** [comment]
why is the width and the height of the screen still stored in the position class? Is this supposed to be here

**Comment by SytzeAndr** [comment]
this is an issue that should be changed in an other branch, it has been there for a long time.

**Comment by spiderbiggen** [comment]
then this is fine and I shall merge this branch

**Pull request merged**
