### PR TITLE
Gui tests < testing,user-interface,configuration

### PR DESCRIPTION
**Pull request by spiderbiggen**

### CODE REVIEW

**Comment by spiderbiggen** [comment]
that last commit is kinda useless but i got messages that the travis build was failing while it was not

**Comment by SytzeAndr** [comment]
I approve

**Comment by Exclaminator** [comment]
The wim test currently just wins by setting size, is there not a more rigorous way to test this, aswell as the loose test? It might be a bit more difficult

**Comment by spiderbiggen** [comment]
@Exclaminator Well you could try to find seeds that make it easy to win but that is very tedious work. It also doesn't really matter since it sets the size just below the game winning size. therefore the shark still needs to collide/eat an enemy

**Comment by Exclaminator** [comment]
Reduving screensize and doing a for loop through seeds and the sysoing the
correct seed might actualy give a deterministic test. And it does matter
because test are now able to randomy fail (small chance) and the winning
test is verry superficial.

**Comment by spiderbiggen** [comment]
@Exclaminator There should not be any chance for the tests to randomly fail because i still use seeds and the winning test, tests for the game to go to the win screen through getting above the winning size by eating a fish which is what i tested

**Comment by MichielvdBerg** [comment]
I approve

**Pull request merged**
