### PR TITLE
tests for the fishController class. 

### PR DESCRIPTION
**Pull request by SytzeAndr**
Coverage is now: Branch=88,9% Line=97.4%

the method for spawning fish with the random chance is a bit harder to test because it requires setting up a random class. Because we can see in our GUI that it actually works, I skipped for now implementing test methods for these 2 lines of code.

### CODE REVIEW

**Comment by MichielvdBerg** [comment]
Checked, a good test percentage, these two lines are not the main focus now, so that's not a problem.

**Comment by spiderbiggen** [comment]
please the master into this branch first please

**Comment by SytzeAndr** [comment]
sure, will do that.

**Comment by SytzeAndr** [comment]
done, branch is ready for merging

**Pull request merged**
