### PR TITLE
Restyle level gui class

### PR DESCRIPTION
**Pull request by SytzeAndr**
I restyled a lot. The gui is now very organized. It involves hierarchies, file splitting and better class responsabilities. It might conflict with other open pull requests. I suggest to first merge this into the master before the other requests, because this one has changes on all fronts based on the gui.

### CODE REVIEW

**Comment by Exclaminator** [comment]
Looks realy realy good!

**Comment by SytzeAndr** [comment]
It now has conflict erros, I should first resolve this before it can be merged

**Comment by SytzeAndr** [comment]
I resolved the conflict errors

**Comment by MichielvdBerg** [comment]
Checked

**Comment by SytzeAndr** [comment]
with 2 people saying yes, I merge this

**Pull request merged**
