### PR TITLE
Pausing game

### PR DESCRIPTION
**Pull request by SytzeAndr**
it works properly. However: there are still 2 bugs I found.
If you are moving the shark, and you pause the screen, the shark is still moving even though the animation timer stopped. The fish on the screen, however, do not move. This problem also counts for laserbullets. I decided it is better to merge this for now with the master, and look for the root of this bug afterwards, so Stefan can start implementing the actual options screen.

Pausegame functionality is implemented by splitting up a lot of methods inside of the gamePane and by making a pauseGameController.

An other bug I found is with eating fishes. A fish is not instantly killed when eaten, what means it is eaten multiple times by a shark. You can hear this in the sound. However: this bug is created in an other branch.

### CODE REVIEW

**Comment by Exclaminator** [comment]
I am unable to find the testclass for pause controller, if you want some inspiration look at the RestartGameController in my branch.

**Comment by SytzeAndr** [comment]
that is indeed true. I couldn't find a proper way of using mockito to check if a static method was called. Because it were just a few instructions, I decided to not make one. But if you managed to make unit tests for the restartGameController (which has the same problem) I could probably make a similar unit test for the pausegame, so I will try that.

**Comment by SytzeAndr** [comment]
I added a unit test. It has a nice 100% coverage.

**Comment by SytzeAndr** [comment]
ah, conflict errors. I will try to resolve them.

**Comment by MichielvdBerg** [comment]
With the new test class and resolved conflicts, I approve.

**Pull request merged**
