### PR TITLE
Volume slider

### PR DESCRIPTION
**Pull request by SytzeAndr**

### CODE REVIEW

**Comment by spiderbiggen** [comment]
If you could also add seperate volumesliders for the music and soundeffect volume then that would be great

**Comment by SytzeAndr** [comment]
I'll leave that for the next pull request

**Comment by Exclaminator** [comment]
Maybe add a transparant white overplay behind the button and slider, for the rest it looks okay

**Comment by SytzeAndr** [comment]
seems also a quite good addition, I'll maybe add it to the next pull request as it is a seperate thing.

**Comment by MichielvdBerg** [comment]
It looks good, I approve.

**Comment by SytzeAndr** [comment]
in that case, I'll merge this into master

**Pull request merged**
