### PR TITLE
Collision behaviour

### PR DESCRIPTION
**Pull request by Exclaminator**
Restructure of game engine, this is not fully done some extra methods are still present, but from this point you can atleast rebase your branch from this.

### CODE REVIEW

**Comment by daanwerf** [comment]
Nice work. Because it was a restructure I did not go through every single file that changed but instead I have runned the code and all the tests. The game still works and all the tests pass. This means i approve of this merge.

**Comment by SytzeAndr** [comment]
I looked trough the code. the strategy pattern is indeed a lot more structured. I think it is best for now to merge this, as this will probably provoke a lot of merge conflicts in other branches.

**Comment by SytzeAndr** [comment]
You said it is not finished, so I will leave this branch open.

**Comment by Exclaminator** [comment]
Verry wel!

**Pull request merged**
