### PR TITLE
Mute sound button

### PR DESCRIPTION
**Pull request by daanwerf**
I have implemented a mute sound button. The button can be found in the bottom left corner of the screen. When the player pressed the button, the music will pause. Pressing the button again will unmute the sound meaning the music will resume.

### CODE REVIEW

**Comment by MichielvdBerg** [comment]
Looks good, I approve

**Comment by SytzeAndr** [comment]
You only mute the musicplayer, not the soundPlayer, which means sound effects still play. I would suggest you make a function something like 'mutePlayer(MediaPlayer player)' which you call for both players. Mutesound could better be renamed as 'muteAllPlayers()'.

**Comment by Exclaminator** [comment]
Maybe it's a good idea to have both options in a options menu?

**Comment by daanwerf** [comment]
@SytzeAndr good point, I will implement that right now. @Exclaminator We could do that, but for now we can just leave it in the bottom corner untill there is a real menu.

**Comment by Exclaminator** [comment]
Looks good, merging

**Pull request merged**
