### PR TITLE
Multi fish implementation

### PR DESCRIPTION
**Pull request by Exclaminator**
Multiple fishses have now been implemented, we might consider upgrading our sprites.

### CODE REVIEW

**Comment by SytzeAndr** [comment]
Check, I think this is the closest we can get with what our TA wants us to implement.

**Comment by spiderbiggen** [comment]
instead of creating a class for each enemy wouldn't it be easier to make an enum with the string of the location and it's width and height?

**Comment by SytzeAndr** [comment]
actually, I agree on this one with stefan. creating 10 classes that only have a few lines of difference in code is not the way to go in my opinion.
Can't you just set a variable string inside the fishbot that could be set and is randomly assigned when we create a new random fish?

**Comment by Exclaminator** [comment]
@SytzeAndr This wasn't the ta assignment, this however was based on the branch where I implemented it, I think it is obvious to look at this and think it should be an enum, an enum however cannot inherit data from non enum non interface classes, one could however implent this in a way of the behaviour pattern (wel will have an excersize in wich we need to implement d.p. next week)

**Comment by SytzeAndr** [comment]
Indeed, my bad. This was indeed not the TA assignment. I think I've mistaken your 2 branches or looked at the last couple of commits and saw the interface things and thought this was about that.
I still don't get it why it has to be implemented in 12 different classes. This looks like a lot of extra code that is not necessary.
Can't you just make a parameter that is an integer from 1 to 12, and based on that number the fishbot uses the corresponding image url? I could give it a try in a seperate branch what I mean.

**Comment by Exclaminator** [comment]
If you where to do that images for enemies could not diverge to other
values, any way you solve this there will always be some downsides, + there
is an assignemnet from next friday in which we can perfectly improve
further upon this.

**Comment by spiderbiggen** [comment]
@Exclaminator but why would the images need to diverge to other values? once they're instantiated they should stay that way.

**Comment by Exclaminator** [comment]
I think you misunderstand me, if you where to use a int t in between [1,
12] and then synthesise the imageurl from it by "image-[t].png" we lock
ourselfs in a format which is not something we want.

On Thu, Sep 24, 2015 at 12:51 PM, Stefan Breetveld <notifications@github.com

**Comment by spiderbiggen** [comment]
@Exclaminator ah yes i misunderstood then

**Comment by SytzeAndr** [comment]
maybe a hashtable with integers connecting to image url's?

**Comment by Exclaminator** [comment]
Why a hashtable, they are mainly for lookup preformance,

but please accept it, the more proper way to do this is with a strategy
pattern,
non of this, and this is something required in the next assignment.

**Comment by SytzeAndr** [comment]
it has merge conflicts with the master, please fix this. After that I will merge

**Comment by spiderbiggen** [comment]
@SytzeAndr after the merge conflicts have been fixed i will check this too

**Comment by Exclaminator** [comment]
I have merged successfully

**Pull request merged**
