### PR TITLE
<optimization, naming, interface, testing, documentation

### PR DESCRIPTION
**Pull request by spiderbiggen**
Also improvements to pmd and findbugs statistics. fixed some of the spelling mistakes that were in the code ... <sup>windows sucks for this</sup>

### CODE REVIEW

**Comment by SytzeAndr** [comment]
2,172 additions and 2,324 deletions.

so I looked trough parts of the changed code, not everything. You did a lot of renaming. Most of the renaming is due to class names that were previously changed, but their methods weren't according to the new class name.

It looks good. We'd better merge it.

**Comment by spiderbiggen** [comment]
@SytzeAndr Maybe merge the other stuff first because sometimes duplicate classes pop up in the travis builds due to the renaming

**Comment by SytzeAndr** [comment]
that is true. I think it is quite easy to merge other branches into this but the other way around could cause problems. Depends on how many are open by now.

**Comment by spiderbiggen** [comment]
@SytzeAndr I believe there are 2 open pull requests besides this one right now

**Comment by MichielvdBerg** [comment]
Now the branch is up to date, I think it can be merged

**Pull request merged**
