### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by Exclaminator**
Feature for logging actions has been added

### CODE REVIEW

**Comment by SytzeAndr** [comment]
First impression: looks good. I will do a code review to look more in detail what and how you implemented this before I merge this.

**Comment by SytzeAndr** [comment]
nice clean way of implementing a logger class. You have my vote to merge.

**Comment by SytzeAndr** [comment]
I resolved the merge conflicts. We need one more person to view this branch before we can merge this with the master.

**Comment by MichielvdBerg** [comment]
Checked

**Pull request merged**
