### PR TITLE
actually rename the package to seaobjects from seaObjects <organisation, naming

### PR DESCRIPTION
**Pull request by spiderbiggen**

### CODE REVIEW

**Comment by Exclaminator** [comment]
Please wait with this for my branch, mine has some heafty modifications and also includes this change (to a bigger extend) but I fear this might give alot of merge conflicts and delay my merge (witch is neede so we can start working on the composite pattern)

**Comment by spiderbiggen** [comment]
@Exclaminator Oh ok I was just doing this to be sure I wouldn't be like this on friday

**Comment by Exclaminator** [comment]
Can this branch be closed?

**Comment by spiderbiggen** [comment]
@Exclaminator yes should be fine

**Pull request closed without merging**
